In [7]:
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv(r'C:\Users\cheng\Documents\GitHub\Data_Mining_Project\UMA_IE500_Data_Mining\hotel_booking_data\hotel_bookings.csv')
data_origiin = pd.read_csv(r'C:\Users\cheng\Documents\GitHub\Data_Mining_Project\UMA_IE500_Data_Mining\hotel_booking_data\hotel_bookings.csv')
# Replace 'NULL' string values with real NaN
data.replace('NULL', np.nan, inplace=True)

# Convert date columns to datetime format
data['arrival_date'] = pd.to_datetime(
    data['arrival_date_year'].astype(str) + '-' +
    data['arrival_date_month'].astype(str) + '-' +
    data['arrival_date_day_of_month'].astype(str),
    errors='coerce'
)

# Drop redundant date parts (optional)
# data.drop(['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month'], axis=1, inplace=True)

# Convert categorical and numeric columns
categorical_cols = data.select_dtypes(include='object').columns
numeric_cols = data.select_dtypes(include='number').columns

# Optional: fix boolean style numeric values
data['is_canceled'] = data['is_canceled'].astype(int)

# Overview of cleaned data
#print(data.info())
#print("\nMissing values per column:\n", data.isnull().sum())
#print("\nSample rows:\n", data.head())

In [6]:
# Show as table
pd.set_option('display.max_columns', None)  # show all columns
pd.set_option('display.width', 1000)        # wider display
display(data.head(10))  # show the first 10 rows as a table

          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  adults  children  babies meal country market_segment distribution_channel  is_repeated_guest  previous_cancellations  previous_bookings_not_canceled reserved_room_type assigned_room_type  booking_changes deposit_type  agent  company  days_in_waiting_list customer_type    adr  required_car_parking_spaces  total_of_special_requests reservation_status reservation_status_date arrival_date
0  Resort Hotel            0        342               2015               July                        27                          1                        0                     0       2       0.0       0   BB     PRT         Direct               Direct                  0                       0                               0                  C                  C                3   No Deposit    NaN      NaN                     0     Transient    0.0                            0                          0          Check-Out              2015-07-01   2015-07-01
1  Resort Hotel            0        737               2015               July                        27                          1                        0                     0       2       0.0       0   BB     PRT         Direct               Direct                  0                       0                               0                  C                  C                4   No Deposit    NaN      NaN                     0     Transient    0.0                            0                          0          Check-Out              2015-07-01   2015-07-01
2  Resort Hotel            0          7               2015               July                        27                          1                        0                     1       1       0.0       0   BB     GBR         Direct               Direct                  0                       0                               0                  A                  C                0   No Deposit    NaN      NaN                     0     Transient   75.0                            0                          0          Check-Out              2015-07-02   2015-07-01
3  Resort Hotel            0         13               2015               July                        27                          1                        0                     1       1       0.0       0   BB     GBR      Corporate            Corporate                  0                       0                               0                  A                  A                0   No Deposit  304.0      NaN                     0     Transient   75.0                            0                          0          Check-Out              2015-07-02   2015-07-01
4  Resort Hotel            0         14               2015               July                        27                          1                        0                     2       2       0.0       0   BB     GBR      Online TA                TA/TO                  0                       0                               0                  A                  A                0   No Deposit  240.0      NaN                     0     Transient   98.0                            0                          1          Check-Out              2015-07-03   2015-07-01
5  Resort Hotel            0         14               2015               July                        27                          1                        0                     2       2       0.0       0   BB     GBR      Online TA                TA/TO                  0                       0                               0                  A                  A                0   No Deposit  240.0      NaN                     0     Transient   98.0                            0                          1          Check-Out              2015-07-03   2015-07-01
6  Resort Hotel            0          0               2015               July                        27                          1                        0                     2       2       0.0       0   BB     PRT         Direct               Direct                  0                       0                               0                  C                  C                0   No Deposit    NaN      NaN                     0     Transient  107.0                            0                          0          Check-Out              2015-07-03   2015-07-01
7  Resort Hotel            0          9               2015               July                        27                          1                        0                     2       2       0.0       0   FB     PRT         Direct               Direct                  0                       0                               0                  C                  C                0   No Deposit  303.0      NaN                     0     Transient  103.0                            0                          1          Check-Out              2015-07-03   2015-07-01
8  Resort Hotel            1         85               2015               July                        27                          1                        0                     3       2       0.0       0   BB     PRT      Online TA                TA/TO                  0                       0                               0                  A                  A                0   No Deposit  240.0      NaN                     0     Transient   82.0                            0                          1           Canceled              2015-05-06   2015-07-01
9  Resort Hotel            1         75               2015               July                        27                          1                        0                     3       2       0.0       0   HB     PRT  Offline TA/TO                TA/TO                  0                       0                               0                  D                  D                0   No Deposit   15.0      NaN                     0     Transient  105.5                            0                          0           Canceled              2015-04-22   2015-07-01

In [9]:
# save the data with the arrival date column
data.to_csv(r'C:\Users\cheng\Documents\GitHub\Data_Mining_Project\UMA_IE500_Data_Mining\hotel_booking_data\hotel_bookings_with_specific_arrival_date.csv', index=False)